# Generated by Django 4.1.2 on 2022-10-31 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivarlab", "0002_alter_publication_category_alter_team_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="category",
            field=models.CharField(
                choices=[
                    ("International Reports", "International Reports"),
                    ("Book Chapters", "Book Chapters"),
                    ("Journal", "Journal"),
                    ("Conference", "Conference"),
                    ("Books", "Books"),
                ],
                default="Journal",
                max_length=60,
            ),
        ),
    ]
