# Generated by Django 4.1.2 on 2022-10-31 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivarlab", "0004_alter_publication_category_alter_team_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reasearch",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("info", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Conference Presentation", "Conference Presentation"),
                            ("Editorial Boards", "Editorial Boards"),
                            ("Invited Talks", "Invited Talks"),
                        ],
                        default="Invited Talks",
                        max_length=60,
                    ),
                ),
                ("date", models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(name="View_count",),
        migrations.AlterField(
            model_name="publication",
            name="category",
            field=models.CharField(
                choices=[
                    ("Journal", "Journal"),
                    ("Books", "Books"),
                    ("International Reports", "International Reports"),
                    ("Book Chapters", "Book Chapters"),
                    ("Conference", "Conference"),
                ],
                default="Journal",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="category",
            field=models.CharField(
                choices=[("ALUMINI", "ALUMINI"), ("TEAM", "TEAM")],
                default="Team",
                max_length=120,
            ),
        ),
    ]
