# Generated by Django 2.2.9 on 2022-11-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivarlab', '0007_auto_20221104_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('International Reports', 'International Reports'), ('Journal', 'Journal'), ('Conference', 'Conference'), ('Book Chapters', 'Book Chapters'), ('Books', 'Books')], default='Journal', max_length=60),
        ),
        migrations.AlterField(
            model_name='reasearch',
            name='category',
            field=models.CharField(choices=[('Editorial Boards', 'Editorial Boards'), ('Conference Presentation', 'Conference Presentation'), ('Invited Talks', 'Invited Talks')], default='Invited Talks', max_length=60),
        ),
    ]
