# Generated by Django 3.2.9 on 2022-11-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivarlab', '0008_auto_20221104_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('International Reports', 'International Reports'), ('Conference', 'Conference'), ('Books', 'Books'), ('Journal', 'Journal'), ('Book Chapters', 'Book Chapters')], default='Journal', max_length=60),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('TEAM', 'TEAM'), ('ALUMINI', 'ALUMINI')], default='Team', max_length=120),
        ),
    ]
